#!/usr/bin/env bash

# pull photos from an sd card to a folder for today's date,
# then prompt if the user wishes to open Darktable or unmount the sd card

FOLDER=~/
MENUCMD=$(which wmenu 2>/dev/null || which dmenu 2>/dev/null) # use wmenu if available, otherwise dmenu

mount() { # Check if the card is mounted
		[ -d /mnt/sdcard/DCIM/ ] || fyi "Card not mounted."
}

unmount() { # Unmount card
		sudo systemd-mount --unmount /mnt/sdcard && fyi "Card unmounted."
}

dt() { # Open darktable to import today's photos
		sudo systemd-mount --unmount /mnt/sdcard && fyi "Card unmounted; opening Darktable"
		(darktable "$folder$(date '+%b_%d')") &
}

postrun() { # Menu to select what I want to do after photos have been transferred
		fyi "Photos have transferred."
		choice=$(printf "Unmount card\\nOpen Darktable, unmount\\nDo nothing" | $MENUCMD -c -l 3 -i -p "Photos have transferred: ")
		case "$choice" in
				Unmount*) unmount;;
				Open*) dt;;
				Do*) exit 0;;
		esac
}

auto() { # Transfer photos from SD card into a directory for today's date
		[ -d /mnt/sdcard/DCIM/ ] || exit 0
		fyi "Photo transfer starting..."

		mkdir -p "$folder$(date '+%b_%d')"
		find /mnt/sdcard -type f -name "*.CR2" -exec mv -nv {} "$FOLDER$(date '+%b_%d')/" \; && postrun
}

case "$1" in
		mount) mount ;;
		unmount) unmount ;;
		dt) dt ;;
		*) auto ;;
esac
